### ISSUE TITLE
There is no description of what Treecord is

### ISSUE THREAD

**Issue by drcouzelis** [Treecord/Treecord#2]
Can you please provide information on what Treecord is? The only information I've found is "a modded Discord client for Android." I briefly read through the very large patch file, it looks like the this project mainly (only?) patches the Discord APK for theme support. Is this correct?

I recommend putting a description in the main README file. Thank you.

**Comment by Juby210** [comment]
Check releases page for features list, but you found a dead mod. Check this one instead https://github.com/Aliucord/Aliucord

**Comment by matyklug18** [comment]
The project is not dead. I have took it over and have not started work on it due to no longer using Discord. That is, the project is currently *stale*, not *dead*. I will edit the README to include information about the project being stale. The main thing that I was working on before was a Lua scripting API.
